# Generated by Django 5.1.3 on 2024-11-12 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errorreport',
            name='application',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='errorreport',
            name='severity',
            field=models.CharField(choices=[('critical', 'Critical'), ('warning', 'Warning'), ('info', 'Info')], max_length=10),
        ),
    ]
